openapi: 3.1.0
info:
  title: comments
  version: '1.0'
  contact:
    name: Gheorghe Avram
    email: gheo@qubuilder.com
  license:
    name: MIT
    identifier: MIT
  description: Small Comments API built on top of Cloudflare Workers.
servers:
  - url: 'https://workers-comments.qubuilder.workers.dev'
    description: Production
paths:
  '/comments/{article}':
    get:
      summary: Get Comments
      operationId: get-comment
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Comment'
                  cursor:
                    type: string
                    description: Cursor for the next page if available
        '500':
          $ref: '#/components/responses/Error'
      parameters:
        - schema:
            type: number
          in: query
          name: limit
          description: Amount of comments to send at once
        - schema:
            type: string
          in: query
          name: cursor
          description: 'Cursor from previous requests, used to deliver next batch'
      description: Gets all the comments of an article.
    post:
      summary: Create a Comment
      operationId: create-comment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Comment'
                - type: object
                  properties:
                    email:
                      type: string
                      format: email
                      description: Email of the author
                  required:
                    - email
        description: ''
      description: Creates a comments for an article.
    parameters:
      - schema:
          type: string
        name: article
        in: path
        required: true
        description: The name of the article
components:
  schemas:
    Comment:
      title: Comment
      type: object
      properties:
        id:
          type: string
          description: Id of Comment
          readOnly: true
        name:
          type: string
          description: Name of the comment author
        content:
          type: string
          description: Comment Content
        profile:
          type: string
          description: URL for Profile Picture
          readOnly: true
        time:
          type: string
          format: date-time
          description: Timestamp comment was created at
          readOnly: true
      required:
        - id
        - name
        - content
        - profile
        - time
  responses:
    Error:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
      headers: {}
